#name: Nasfame
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#  schedule:
#    - cron: '*/5 * * * *'
#
#concurrency:
#  group: Nasfame
#  cancel-in-progress: true
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#
#    environment: Nasfame
#
#    # env:
#    #   GIT_PASS: ${{ secrets.GIT_PASS }}
#    #   SLEEP_TIME: .0001
#
#    env:
#      SLEEP_TIME: .00001
#      GIT_PASS: ${{ secrets.GIT_PASS }}
#      GIT_USERNAME: ${{vars.GIT_USERNAME}}
#      GIT_EMAIL: ${{vars.GIT_EMAIL}}
#      GIT_REPO: ${{vars.GIT_REPO}}
#
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Python 3.10 on ubuntu-latest
#        uses: actions/setup-python@v3
#        with:
#          python-version: "3.10"
#      #          cache: 'pip' requirements.txt required
#
#      - name: Run time cacher
#        run: |
#          python main.py