name: Time Catcher

on:
  push:
    branches: ["main"]
    tags:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

  schedule:
    - cron: "* */1 * * *"

concurrency:
  group: time-catcher
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      fail-fast: false

      matrix:
        GIT_REPO:
          - Nasfame/___time_2023
          - Nasfame/___time
          - funFame/_time
          - funFame/__time
          - funFame/_time_2023
          - funFame/__time_2023

    env:
      GIT_PASS: ${{ secrets.GIT_PASS }}
      GH_TOKEN: ${{ secrets.TOKEN_GITHUB || github.token }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB || github.token }}
      GIT_USERNAME: Nasfame
      GIT_EMAIL: laciferin@gmail.com
      GIT_USER: Hiro
      GIT_REPO: ${{ matrix.GIT_REPO }}
      NO_OF_COMMITS: 200
      SLEEP_TIME: 1

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10 on ubuntu-latest
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      #          cache: 'pip'
      - name: Clean up
        continue-on-error: true
        run: |
          gh run list --limit 1000 --json databaseId \
            | jq '.[].databaseId' \
            | xargs -P 20 -I {} gh api --method DELETE /repos/sync-laciferin2024/fork-sync/actions/runs/{}

      - name: Run time cacher for ${{env.GIT_REPO}}
        run: |
          python main.py
