name: Time Catcher

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: '*/20 * * * *'

concurrency:
  group: time-catcher
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_PASS: ${{ secrets.GIT_PASS }}
      SLEEP_TIME: 0
      GIT_USERNAME: pythoneerHiro
      GIT_USER: Hiro
      GIT_REPO: "pythoneerHiro/__time-catcher"
      NO_OF_COMMITS: 100000

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10 on ubuntu-latest
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      #          cache: 'pip'

      - name: Run time cacher
        run: |
          python main.py