name: Time Catcher

on:
  push:
    branches: [ "main" ]
    tag:
      - "*"
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

concurrency:
  group: time-catcher
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      GIT_PASS: ${{ secrets.GIT_PASS }}
      GIT_USERNAME: Nasfame
      GIT_USER: Hiro
      GIT_REPO: "funFame/_time"
      NO_OF_COMMITS: 1000
      SLEEP_TIME: 1

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10 on ubuntu-latest
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      #          cache: 'pip'

      - name: Run time cacher
        run: |
          python main.py